/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'clothes' : null } |
  { 'technology' : null } |
  { 'phone_accessories' : null } |
  { 'fashion' : null };
export interface Post {
  'id' : bigint,
  'coverImageUrl' : [] | [string],
  'title' : string,
  'body' : string,
  'createdAt' : Time,
  'authorName' : string,
  'category' : Category,
}
export interface PostInput {
  'coverImageUrl' : [] | [string],
  'title' : string,
  'body' : string,
  'authorName' : string,
  'category' : Category,
}
export interface Score { 'score' : bigint, 'playerName' : string }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addScore' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[PostInput], bigint>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getPostsByCategory' : ActorMethod<[Category], Array<Post>>,
  'getTopScores' : ActorMethod<[], Array<Score>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePost' : ActorMethod<[bigint, PostInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];