/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'clothes' : IDL.Null,
  'technology' : IDL.Null,
  'phone_accessories' : IDL.Null,
  'fashion' : IDL.Null,
});
export const PostInput = IDL.Record({
  'coverImageUrl' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'body' : IDL.Text,
  'authorName' : IDL.Text,
  'category' : Category,
});
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'coverImageUrl' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'authorName' : IDL.Text,
  'category' : Category,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Score = IDL.Record({ 'score' : IDL.Nat, 'playerName' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([PostInput], [IDL.Nat], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getPostsByCategory' : IDL.Func([Category], [IDL.Vec(Post)], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePost' : IDL.Func([IDL.Nat, PostInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'clothes' : IDL.Null,
    'technology' : IDL.Null,
    'phone_accessories' : IDL.Null,
    'fashion' : IDL.Null,
  });
  const PostInput = IDL.Record({
    'coverImageUrl' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'body' : IDL.Text,
    'authorName' : IDL.Text,
    'category' : Category,
  });
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'coverImageUrl' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'authorName' : IDL.Text,
    'category' : Category,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Score = IDL.Record({ 'score' : IDL.Nat, 'playerName' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([PostInput], [IDL.Nat], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getPostsByCategory' : IDL.Func([Category], [IDL.Vec(Post)], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePost' : IDL.Func([IDL.Nat, PostInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };